name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job_name: # 원하는 작업의 이름을 정의합니다.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      # 여기에 추가적인 단계를 정의할 수 있습니다.
