name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job_name:
  name: testtt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      # 여기에 추가적인 단계를 정의할 수 있습니다.
